---
- name: Ensure miniconda is installed and initialised
  hosts: all
  tasks:

    - name: Download miniconda3 installer
      ansible.builtin.get_url:
        # url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-{{ ansible_architecture }}.sh
        dest: ~/install-miniconda3.sh
        mode: 0755

    - name: Ensure miniconda is installed
      ansible.builtin.command:
        cmd: bash ~/install-miniconda3.sh -b -u
        creates: ~/miniconda3 # Check miniconda dir is not already present

    - name: Ensure miniconda is initialized
      ansible.builtin.command: ~/miniconda3/bin/conda init
      changed_when: false # Conda init script is idempotent by itself

    # - name: Ensure openstack python venv is present
