---
- name: Ensure kubernetes tooling is configured
  hosts: all
  tasks:

    - name: Ensure k8s tools are snap-installed on Ubuntu
      become: true
      community.general.snap:
        name:
          - kubectl
          - helm
          - kubectx
          - k9s
        state: present
        classic: true
      when: ansible_distribution == 'Ubuntu'

    - name: Ensure useful packages system packages are present
      become: true
      ansible.builtin.package:
        name:
          - kubecolor
        state: present

    - name: Ensure desired config is in .bash_profile
      ansible.builtin.blockinfile:
        path: ~/.bash_profile
        marker: "# {mark}: Kubernetes aliases"
        block: |
          alias k=kubectl
          alias ka="kubectl apply -f"
          # Enable kubectl auto-completion
          source <(kubectl completion bash)
          # Extend auto-completion to 'k=kubectl' alias
          complete -o default -F __start_kubectl k
        create: true
        mode: 0644
