---

- name: Ensure basic config and packages are present
  hosts: all
  tasks:

    - name: Check OS distribution
      debug:
        var: ansible_distribution

    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == 'Ubuntu'

    - name: Ensure useful packages system packages are present
      become: true
      ansible.builtin.package:
        name:
          - gcc
          - git
          - unzip
          - python3-dev
          - python3-venv
          - python3-pip
          - tmux
          - nano
          - less
        state: present

    - name: Ensure desired config is in .bashrc
      ansible.builtin.blockinfile:
        path: ~/.bashrc
        marker: "# {mark}: Ansible-managed basic aliases"
        block: |

          # Make sure ssh-agent is running
          # [[ -z $SSH_AUTH_SOCK ]] && eval `ssh-agent`
          #Increase max size of .bash_history file
          HISTSIZE=100000
          #Force history to be appended to after each command instead of on session logout
          PROMPT_COMMAND='history -a'
        
        create: true
        mode: 0644


    - name: Ensure desired config is in .bash_profile
      ansible.builtin.blockinfile:
        path: ~/.bash_profile
        marker: "# {mark}: Ansible-managed basic aliases"
        block: |

          [[ -f ~/.profile ]] && source ~/.profile
          alias ll="ls -l"
          alias la="ls -a"
        
        create: true
        mode: 0644

    - name: Ensure .inputrc file is configured
      ansible.builtin.blockinfile:
        path: ~/.inputrc
        marker: "# {mark}: Enable history search with arrow keys"
        block: |

          "\e[A": history-search-backward
          "\e[B": history-search-forward
          set colored-stats On
          
        create: true
        mode: 0644

    - name: Ensure .tmux.conf file is configured
      ansible.builtin.blockinfile:
        path: ~/.tmux.conf
        marker: "# {mark}: Ansible managed tmux config"
        block: |

          # Auto-switch to scroll mode when mouse scrolling detected
          setw -g mouse on
          # Increase size of scroll back history
          set-option -g history-limit 25000
          # Colorize terminal prompt correctly
          set -g default-terminal "tmux-256color"

        create: true
        mode: 0644

    - name: Ensure .zshrc file is configured
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        marker: "# {mark}: Ansible-managed zsh config"
        block: |

          # Customize terminal prompt
          PROMPT='%F{green}%*%f:%F{blue}%~%f %% ' #Time and working dir with colour

          # Set up/down arrows to search history containing partially typed command
          bindkey "^[[A" history-beginning-search-backward
          bindkey "^[[B" history-beginning-search-forward

          # Configure shell history
          setopt HIST_IGNORE_ALL_DUPS
          setopt INC_APPEND_HISTORY
          setopt SHARE_HISTORY
          SAVEHIST=100000

          # Convenient aliases
          alias la='ls -a'
          alias ll='ls -l'

        create: true
        mode: 0644

    - name: Ensure .vimrc file is configured
      ansible.builtin.blockinfile:
        path: ~/.vimrc
        marker: "# {mark}: Ansible-managed vim config"
        block: |
          autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
        create: true
        mode: 0644