---

# - name: Ensure multipass host is ssh-able
#   hosts: localhost
#   tasks:
#     - name: "Ensure ssh key is present on multipass vm"
#       ansible.builtin.shell: cat ~/.ssh/id_rsa.pub | multipass exec test-vm -- tee -a ~/.ssh/authorized_keys
#         # pipefail:
#       changed_when: true

- name: Configure remote VM
  hosts: all
  vars:
    github_ssh_key: ~/.ssh/keys/github_id_rsa
  tasks:

    - name: Debugging
      ansible.builtin.debug:
        var: github_ssh_key

    - name: Ensure useful packages from system package manager are present and up to date
      become: true
      ansible.builtin.package:
        name:
          - git
          - python3-dev
          - tmux
          - nano
        state: present

    - name: Download miniconda3 installer
      ansible.builtin.get_url:
        # url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-{{ ansible_architecture }}.sh
        dest: ~/install-miniconda3.sh
        mode: 0755

    - name: Ensure miniconda is installed
      ansible.builtin.command:
        cmd: bash ~/install-miniconda3.sh -b -u
        creates: ~/miniconda3 # Check miniconda dir is not already present

    - name: Ensure miniconda is initialized
      ansible.builtin.command: ~/miniconda3/bin/conda init
      changed_when: false # Conda init script is idempotent by itself

    - name: Ensure github ssh key is present
      ansible.builtin.copy:
        src: "{{ github_ssh_key }}"
        dest: ~/.ssh/github_id_rsa
        mode: 0600

    - name: Ensure github ssh config entry exists
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        block: |
          Host github.com
            HostName github.com
            IdentityFile ~/.ssh/github_id_rsa
        create: true
        mode: 0644
