---
- name: Ensure github ssh access is configured
  hosts: all
  vars:
    ssh_key: ~/.ssh/keys/github_id_rsa
    # ssh_key: ~/.ssh/id_rsa
  tasks:

    - name: Ensure github ssh key is present
      ansible.builtin.copy:
        src: "{{ ssh_key }}"
        dest: ~/.ssh/github_id_rsa
        mode: 0600

    - name: Ensure github ssh config entry exists
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        marker: "# {mark}: Ansible managed github config"
        block: |
          Host github.com
            HostName github.com
            IdentityFile ~/.ssh/github_id_rsa
        create: true
        mode: 0644
